# Generated by Django 5.2.15 on 2026-06-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='funciones', to='users.rol'),
        ),
        migrations.AddField(
            model_name='funcion',
            name='modulos',
            field=models.ManyToManyField(blank=True, related_name='funciones', to='modules.modulo'),
        ),
    ]
