# Generated by Django 5.2.15 on 2026-06-16 13:06

import django.core.validators
import django.db.models.deletion
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id_funcion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_funcion', models.CharField(max_length=100, unique=True)),
                ('estado_funcion', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'funciones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_name', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(8, message='El usuario debe tener mínimo 8 caracteres.')])),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[users.models.validate_email_domain])),
                ('correo_verificado', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verification_tokens',
            },
        ),
        migrations.CreateModel(
            name='FuncionRol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('funcion', models.ForeignKey(db_column='funcion_id', on_delete=django.db.models.deletion.CASCADE, to='users.funcion')),
            ],
            options={
                'db_table': 'funciones_roles',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100, unique=True)),
                ('estado_rol', models.BooleanField(default=True)),
                ('funciones', models.ManyToManyField(related_name='roles', through='users.FuncionRol', to='users.funcion')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='funcionrol',
            name='rol',
            field=models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.CASCADE, to='users.rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='users.rol'),
        ),
    ]
