# Generated by Django 5.2.15 on 2026-06-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rol',
            table='roles',
        ),
    ]
