# Generated by Django 5.2.15 on 2026-06-09 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_rol_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
