# Generated by Django 5.2.15 on 2026-06-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rol_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlIP',
            fields=[
                ('ip_usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'control_ips',
            },
        ),
    ]
