# Generated by Django 5.2.15 on 2026-07-01 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_remove_modulo_funciones_delete_funcionmodulo'),
        ('users', '0003_add_control_ips_and_auditoria_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='modulo',
            field=models.ForeignKey(blank=True, db_column='modulo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='modules.modulo'),
        ),
    ]
