# Generated by Django 5.2.15 on 2026-07-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_funcion_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='token',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
