# Generated by Django 5.2.15 on 2026-07-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_passwordresettoken_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
