# Generated by Django 5.2.15 on 2026-06-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionModulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'funciones_modulos',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modulo', models.CharField(max_length=100)),
                ('descripcion_modulo', models.CharField(max_length=255)),
                ('estado_modulo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'modulos',
            },
        ),
    ]
