# Generated by Django 5.2.15 on 2026-06-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id_funcion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_funcion', models.CharField(max_length=100)),
                ('estado_funcion', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modulo', models.CharField(max_length=100)),
                ('descripcion_modulo', models.TextField(blank=True, null=True)),
                ('estado_modulo', models.BooleanField(default=True)),
            ],
        ),
    ]
