# Generated by Django 5.2.15 on 2026-06-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionmodulo',
            name='funcion',
            field=models.ForeignKey(db_column='funcion_id', on_delete=django.db.models.deletion.CASCADE, to='users.funcion'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='funciones',
            field=models.ManyToManyField(related_name='modulos', through='modules.FuncionModulo', to='users.funcion'),
        ),
        migrations.AddField(
            model_name='funcionmodulo',
            name='modulo',
            field=models.ForeignKey(db_column='modulo_id', on_delete=django.db.models.deletion.CASCADE, to='modules.modulo'),
        ),
    ]
