# Generated by Django 5.2.15 on 2026-07-01 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_funcionmodulo_funcion_funcionmodulo_modulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='funciones',
        ),
        migrations.DeleteModel(
            name='FuncionModulo',
        ),
    ]
