# Generated by Django 5.2.15 on 2026-06-09 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcion',
            table='funciones',
        ),
        migrations.AlterModelTable(
            name='modulo',
            table='modulos',
        ),
    ]
