# Generated by Django 5.2.15 on 2026-06-08 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='id_funciones',
            field=models.ForeignKey(db_column='id_funciones', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.funcion'),
        ),
    ]
