# Generated by Django 5.2.15 on 2026-06-16 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='id_funciones',
            field=models.ForeignKey(db_column='id_funciones', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.funcion'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='username',
            field=models.ForeignKey(db_column='username', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='user_name'),
        ),
    ]
