# Generated by Django 5.2.15 on 2026-06-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditoria_id_funciones_auditoria_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='modulo',
            field=models.CharField(blank=True, help_text='Módulo externo que generó la pista (ej. INVENTARIO, FACTURACION)', max_length=100, null=True),
        ),
    ]
